import pytest
from app.schemas.analysis import SpeechResult, SpeechSegment
from app.services.fraud_engine import FraudIntentEngine


@pytest.fixture
def fraud_engine():
    return FraudIntentEngine()


def test_1_high_fraud_ceo_scam(fraud_engine):
    """
    Test Case 1: High-risk CEO wire scam with urgency, secrecy, and payment request.
    """
    segments = [
        SpeechSegment(
            start_s=0.0,
            end_s=3.0,
            text="This is the CEO speaking. We have an urgent acquisition deal.",
        ),
        SpeechSegment(
            start_s=3.0,
            end_s=6.0,
            text="Transfer funds immediately to the new account number and keep this strictly confidential.",
        ),
    ]
    speech = SpeechResult(
        available=True,
        model="faster-whisper-base-int8",
        status="completed",
        language="en",
        duration_s=6.0,
        text="This is the CEO speaking. We have an urgent acquisition deal. Transfer funds immediately to the new account number and keep this strictly confidential.",
        segments=segments,
    )

    result = fraud_engine.analyze(speech)
    assert result.level == "HIGH"
    assert any(cat.category == "AUTHORITY" for cat in result.categories)
    assert any(cat.category == "URGENCY" for cat in result.categories)
    assert any(cat.category == "SECRECY" for cat in result.categories)
    assert any(cat.category == "PAYMENT_CREDENTIAL" for cat in result.categories)
    assert any(act.action == "TRANSFER_MONEY" for act in result.requested_actions)
    assert not result.news_context_downgrade


def test_2_subjective_financial_need_i_need_money(fraud_engine):
    """
    Test Case 2: Subjective statement 'I need money' must NOT trigger PAYMENT_CREDENTIAL or action.
    """
    segments = [
        SpeechSegment(
            start_s=0.0,
            end_s=3.0,
            text="I need money to pay my rent this month.",
        ),
    ]
    speech = SpeechResult(
        available=True,
        model="faster-whisper-base-int8",
        status="completed",
        language="en",
        duration_s=3.0,
        text="I need money to pay my rent this month.",
        segments=segments,
    )

    result = fraud_engine.analyze(speech)
    assert result.level == "LOW"
    assert len(result.requested_actions) == 0
    assert not any(cat.category == "PAYMENT_CREDENTIAL" for cat in result.categories)


def test_3_harmless_ai_media_morgan_freeman(fraud_engine):
    """
    Test Case 3: Benign speech (Morgan Freeman AI clip).
    """
    segments = [
        SpeechSegment(
            start_s=0.0,
            end_s=4.0,
            text="I am not Morgan Freeman, and what you see is not real.",
        ),
        SpeechSegment(
            start_s=4.0,
            end_s=8.0,
            text="What would you say if I told you that my voice was generated by an AI model?",
        ),
    ]
    speech = SpeechResult(
        available=True,
        model="faster-whisper-base-int8",
        status="completed",
        language="en",
        duration_s=8.0,
        text="I am not Morgan Freeman, and what you see is not real. What would you say if I told you that my voice was generated by an AI model?",
        segments=segments,
    )

    result = fraud_engine.analyze(speech)
    assert result.level == "LOW"
    assert len(result.requested_actions) == 0
    assert len(result.categories) == 0


def test_4_news_report_downgrade(fraud_engine):
    """
    Test Case 4: News report discussing a scam -> Downgrade applied.
    """
    segments = [
        SpeechSegment(
            start_s=0.0,
            end_s=5.0,
            text="In this news report, police warn that scammers try to make victims wire money immediately.",
        ),
    ]
    speech = SpeechResult(
        available=True,
        model="faster-whisper-base-int8",
        status="completed",
        language="en",
        duration_s=5.0,
        text="In this news report, police warn that scammers try to make victims wire money immediately.",
        segments=segments,
    )

    result = fraud_engine.analyze(speech)
    assert result.news_context_downgrade is True
    # Downgraded from HIGH -> MEDIUM
    assert result.level == "MEDIUM"


def test_5_direct_request_can_you_send_me_money(fraud_engine):
    """
    Test Case 5: Direct request 'Can you send me money?' -> SEND_MONEY action.
    """
    segments = [
        SpeechSegment(
            start_s=0.0,
            end_s=3.0,
            text="Can you send me money for the concert tickets?",
        ),
    ]
    speech = SpeechResult(
        available=True,
        model="faster-whisper-base-int8",
        status="completed",
        language="en",
        duration_s=3.0,
        text="Can you send me money for the concert tickets?",
        segments=segments,
    )

    result = fraud_engine.analyze(speech)
    assert any(act.action == "SEND_MONEY" for act in result.requested_actions)
    # Without urgency/authority/threat, casual request is MEDIUM (or LOW)
    assert result.level == "MEDIUM"


def test_6_direct_request_send_rupees_immediately(fraud_engine):
    """
    Test Case 6: 'Send me ₹50,000 immediately.' -> SEND_MONEY + URGENCY -> HIGH.
    """
    segments = [
        SpeechSegment(
            start_s=0.0,
            end_s=3.0,
            text="Send me ₹50,000 immediately or your account will be blocked.",
        ),
    ]
    speech = SpeechResult(
        available=True,
        model="faster-whisper-base-int8",
        status="completed",
        language="en",
        duration_s=3.0,
        text="Send me ₹50,000 immediately or your account will be blocked.",
        segments=segments,
    )

    result = fraud_engine.analyze(speech)
    assert result.level == "HIGH"
    assert any(act.action == "SEND_MONEY" for act in result.requested_actions)
    assert any(cat.category == "URGENCY" for cat in result.categories)


def test_7_ceo_transfer_rupees(fraud_engine):
    """
    Test Case 7: 'I am your CEO. I need you to transfer ₹50,000 immediately.' -> HIGH.
    """
    segments = [
        SpeechSegment(
            start_s=0.0,
            end_s=4.0,
            text="I am your CEO. I need you to transfer ₹50,000 immediately.",
        ),
    ]
    speech = SpeechResult(
        available=True,
        model="faster-whisper-base-int8",
        status="completed",
        language="en",
        duration_s=4.0,
        text="I am your CEO. I need you to transfer ₹50,000 immediately.",
        segments=segments,
    )

    result = fraud_engine.analyze(speech)
    assert result.level == "HIGH"
    assert any(cat.category == "AUTHORITY" for cat in result.categories)
    assert any(act.action == "TRANSFER_MONEY" for act in result.requested_actions)
    assert any(cat.category == "URGENCY" for cat in result.categories)


def test_8_send_money_and_secrecy(fraud_engine):
    """
    Test Case 8: 'I need you to send me money and don't tell anyone.' -> HIGH.
    """
    segments = [
        SpeechSegment(
            start_s=0.0,
            end_s=4.0,
            text="I need you to send me money and don't tell anyone.",
        ),
    ]
    speech = SpeechResult(
        available=True,
        model="faster-whisper-base-int8",
        status="completed",
        language="en",
        duration_s=4.0,
        text="I need you to send me money and don't tell anyone.",
        segments=segments,
    )

    result = fraud_engine.analyze(speech)
    assert result.level == "HIGH"
    assert any(act.action == "SEND_MONEY" for act in result.requested_actions)
    assert any(cat.category == "SECRECY" for cat in result.categories)


def test_9_otp_and_remote_access(fraud_engine):
    """
    Test Case 9: Direct OTP and AnyDesk installation demands -> HIGH.
    """
    speech_otp = SpeechResult(
        available=True,
        model="faster-whisper-base-int8",
        status="completed",
        language="en",
        duration_s=4.0,
        text="This is technical support. Please install AnyDesk and share your OTP verification code right now.",
        segments=[
            SpeechSegment(
                start_s=0.0,
                end_s=4.0,
                text="This is technical support. Please install AnyDesk and share your OTP verification code right now.",
            )
        ],
    )
    result = fraud_engine.analyze(speech_otp)
    assert result.level == "HIGH"
    assert any(act.action == "INSTALL_REMOTE_ACCESS" for act in result.requested_actions)
    assert any(act.action == "SHARE_OTP" for act in result.requested_actions)


def test_10_no_speech(fraud_engine):
    """
    Test Case 10: No speech available.
    """
    speech_empty = SpeechResult(
        available=False,
        model="faster-whisper-base-int8",
        status="not_available",
        language=None,
        duration_s=0.0,
        text="",
        segments=[],
    )
    result = fraud_engine.analyze(speech_empty)
    assert result.level == "NOT_ASSESSABLE"


def test_11_joke_send_me_money_bro(fraud_engine):
    """Jokes with emojis: 'send me money bro 😂' -> LOW."""
    speech = SpeechResult(
        available=True,
        model="faster-whisper-base-int8",
        status="completed",
        language="en",
        duration_s=3.0,
        text="send me money bro 😂",
        segments=[SpeechSegment(start_s=0.0, end_s=3.0, text="send me money bro 😂")],
    )
    res = fraud_engine.analyze(speech)
    assert res.level == "LOW"


def test_12_legitimate_conversation_debt(fraud_engine):
    """Legitimate conversation: 'Can you send me the money you owe me?' -> LOW."""
    speech = SpeechResult(
        available=True,
        model="faster-whisper-base-int8",
        status="completed",
        language="en",
        duration_s=3.0,
        text="Can you send me the money you owe me for lunch?",
        segments=[SpeechSegment(start_s=0.0, end_s=3.0, text="Can you send me the money you owe me for lunch?")],
    )
    res = fraud_engine.analyze(speech)
    assert res.level == "LOW"


def test_13_news_police_warning(fraud_engine):
    """News: 'Police warned people not to send money.' -> news downgrade / LOW."""
    speech = SpeechResult(
        available=True,
        model="faster-whisper-base-int8",
        status="completed",
        language="en",
        duration_s=4.0,
        text="Police warned people not to send money to unknown callers.",
        segments=[SpeechSegment(start_s=0.0, end_s=4.0, text="Police warned people not to send money to unknown callers.")],
    )
    res = fraud_engine.analyze(speech)
    assert res.news_context_downgrade is True or res.level == "LOW"


def test_14_educational_never_share_otp(fraud_engine):
    """Educational: 'Never share your OTP.' -> LOW, no SHARE_OTP action."""
    speech = SpeechResult(
        available=True,
        model="faster-whisper-base-int8",
        status="completed",
        language="en",
        duration_s=3.0,
        text="Never share your OTP with anyone.",
        segments=[SpeechSegment(start_s=0.0, end_s=3.0, text="Never share your OTP with anyone.")],
    )
    res = fraud_engine.analyze(speech)
    assert res.level == "LOW"
    assert not any(act.action == "SHARE_OTP" for act in res.requested_actions)


def test_15_scam_send_otp_immediately(fraud_engine):
    """Scam: 'Send me your OTP immediately.' -> HIGH."""
    speech = SpeechResult(
        available=True,
        model="faster-whisper-base-int8",
        status="completed",
        language="en",
        duration_s=3.0,
        text="Send me your OTP immediately right now.",
        segments=[SpeechSegment(start_s=0.0, end_s=3.0, text="Send me your OTP immediately right now.")],
    )
    res = fraud_engine.analyze(speech)
    assert res.level == "HIGH"
    assert any(act.action == "SHARE_OTP" for act in res.requested_actions)


def test_16_authority_manager_transfer_money_now(fraud_engine):
    """Authority: 'I am your manager. Transfer the money now.' -> HIGH."""
    speech = SpeechResult(
        available=True,
        model="faster-whisper-base-int8",
        status="completed",
        language="en",
        duration_s=4.0,
        text="I am your manager. Transfer the money now immediately.",
        segments=[SpeechSegment(start_s=0.0, end_s=4.0, text="I am your manager. Transfer the money now immediately.")],
    )
    res = fraud_engine.analyze(speech)
    assert res.level == "HIGH"
    assert any(act.action in ("TRANSFER_MONEY", "SEND_MONEY") for act in res.requested_actions)


def test_17_indirect_card_not_working_transfer(fraud_engine):
    """Indirect: 'My card isn't working. Can you make a small transfer?' -> detects TRANSFER_MONEY."""
    speech = SpeechResult(
        available=True,
        model="faster-whisper-base-int8",
        status="completed",
        language="en",
        duration_s=4.0,
        text="My card isn't working. Can you make a small transfer?",
        segments=[SpeechSegment(start_s=0.0, end_s=4.0, text="My card isn't working. Can you make a small transfer?")],
    )
    res = fraud_engine.analyze(speech)
    assert any(act.action == "TRANSFER_MONEY" for act in res.requested_actions)


def test_18_direct_threat_if_you_dont_pay_i_will_hurt_him(fraud_engine):
    """Direct threat: 'If you don't pay, I will hurt him.' -> HIGH."""
    speech = SpeechResult(
        available=True,
        model="faster-whisper-base-int8",
        status="completed",
        language="en",
        duration_s=4.0,
        text="If you don't pay, I will hurt him.",
        segments=[SpeechSegment(start_s=0.0, end_s=4.0, text="If you don't pay, I will hurt him.")],
    )
    res = fraud_engine.analyze(speech)
    assert res.level == "HIGH"
    assert any(cat.category == "THREAT_PRESSURE" for cat in res.categories)
    assert not res.news_context_downgrade


def test_19_ransom_send_lakh_or_never_see_him_again(fraud_engine):
    """Ransom: 'Send ₹5 lakh or you will never see him again.' -> HIGH."""
    speech = SpeechResult(
        available=True,
        model="faster-whisper-base-int8",
        status="completed",
        language="en",
        duration_s=4.0,
        text="Send ₹5 lakh or you will never see him again.",
        segments=[SpeechSegment(start_s=0.0, end_s=4.0, text="Send ₹5 lakh or you will never see him again.")],
    )
    res = fraud_engine.analyze(speech)
    assert res.level == "HIGH"
    assert any(act.action == "SEND_MONEY" for act in res.requested_actions)
    assert any(cat.category == "THREAT_PRESSURE" for cat in res.categories)
    assert not res.news_context_downgrade


def test_20_secrecy_dont_tell_the_police(fraud_engine):
    """Secrecy: 'Don't tell the police.' -> detects SECRECY and KEEP_SECRET."""
    speech = SpeechResult(
        available=True,
        model="faster-whisper-base-int8",
        status="completed",
        language="en",
        duration_s=3.0,
        text="Don't tell the police.",
        segments=[SpeechSegment(start_s=0.0, end_s=3.0, text="Don't tell the police.")],
    )
    res = fraud_engine.analyze(speech)
    assert any(cat.category == "SECRECY" for cat in res.categories)
    assert any(act.action == "KEEP_SECRET" for act in res.requested_actions)


def test_21_combined_send_money_dont_tell_anyone_or_he_gets_hurt(fraud_engine):
    """Combined: 'Send the money now. Don't tell anyone or he gets hurt.' -> HIGH."""
    speech = SpeechResult(
        available=True,
        model="faster-whisper-base-int8",
        status="completed",
        language="en",
        duration_s=4.0,
        text="Send the money now. Don't tell anyone or he gets hurt.",
        segments=[SpeechSegment(start_s=0.0, end_s=4.0, text="Send the money now. Don't tell anyone or he gets hurt.")],
    )
    res = fraud_engine.analyze(speech)
    assert res.level == "HIGH"
    assert any(act.action == "SEND_MONEY" for act in res.requested_actions)
    assert any(cat.category == "SECRECY" for cat in res.categories)
    assert any(cat.category == "THREAT_PRESSURE" for cat in res.categories)
    assert not res.news_context_downgrade


def test_22_news_police_warned_criminals_ask_for_money(fraud_engine):
    """News: 'Police warned that criminals ask victims for money.' -> appropriately downgraded."""
    speech = SpeechResult(
        available=True,
        model="faster-whisper-base-int8",
        status="completed",
        language="en",
        duration_s=4.0,
        text="Police warned that criminals ask victims for money.",
        segments=[SpeechSegment(start_s=0.0, end_s=4.0, text="Police warned that criminals ask victims for money.")],
    )
    res = fraud_engine.analyze(speech)
    assert res.news_context_downgrade is True or res.level == "LOW"


def test_23_educational_never_send_money_to_someone_threatening(fraud_engine):
    """Educational: 'Never send money to someone threatening you.' -> LOW."""
    speech = SpeechResult(
        available=True,
        model="faster-whisper-base-int8",
        status="completed",
        language="en",
        duration_s=4.0,
        text="Never send money to someone threatening you.",
        segments=[SpeechSegment(start_s=0.0, end_s=4.0, text="Never send money to someone threatening you.")],
    )
    res = fraud_engine.analyze(speech)
    assert res.level == "LOW"
    assert not any(act.action == "SEND_MONEY" for act in res.requested_actions)


def test_24_joke_ill_kill_you_laughing(fraud_engine):
    """Joke: 'I'll kill you 😂' in casual laughing banter -> LOW."""
    speech = SpeechResult(
        available=True,
        model="faster-whisper-base-int8",
        status="completed",
        language="en",
        duration_s=3.0,
        text="I'll kill you 😂",
        segments=[SpeechSegment(start_s=0.0, end_s=3.0, text="I'll kill you 😂")],
    )
    res = fraud_engine.analyze(speech)
    assert res.level == "LOW"


def test_25_legitimate_ill_report_this_to_police_if_dont_return_money(fraud_engine):
    """Legitimate dispute: 'I'll report this to the police if you don't return my money.' -> LOW."""
    speech = SpeechResult(
        available=True,
        model="faster-whisper-base-int8",
        status="completed",
        language="en",
        duration_s=4.0,
        text="I'll report this to the police if you don't return my money.",
        segments=[SpeechSegment(start_s=0.0, end_s=4.0, text="I'll report this to the police if you don't return my money.")],
    )
    res = fraud_engine.analyze(speech)
    assert res.level == "LOW"


def test_26_indirect_if_you_care_about_him_arrange_money(fraud_engine):
    """Indirect extortion: 'If you care about him, you'll arrange the money.' -> HIGH."""
    speech = SpeechResult(
        available=True,
        model="faster-whisper-base-int8",
        status="completed",
        language="en",
        duration_s=4.0,
        text="If you care about him, you'll arrange the money.",
        segments=[SpeechSegment(start_s=0.0, end_s=4.0, text="If you care about him, you'll arrange the money.")],
    )
    res = fraud_engine.analyze(speech)
    assert res.level == "HIGH"
    assert any(act.action == "SEND_MONEY" for act in res.requested_actions)
    assert any(cat.category == "THREAT_PRESSURE" for cat in res.categories)


def test_27_known_real_person_high_threat_case(fraud_engine):
    """
    P9 Regression Test: Known Real-Person High-Threat Case
    "Your boy is in my hand, Mr."
    "Give me 10 crore rupees and I will think about releasing him"
    "Don't even tell the police, I will kill him if I want to"

    Expected:
      fraud = HIGH
      requested_actions includes SEND_MONEY
      categories includes THREAT_PRESSURE
      categories includes SECRECY
      news_context_downgrade = False
      action = STOP_AND_VERIFY
    """
    from app.schemas.evidence import EvidenceMatrix, EvidenceModalityResult, ProvenanceResult
    from app.schemas.reliability import ReliabilityResult
    from app.services.assessment_service import AssessmentService

    segments = [
        SpeechSegment(start_s=0.0, end_s=2.5, text="Your boy is in my hand, Mr."),
        SpeechSegment(start_s=2.5, end_s=5.5, text="Give me 10 crore rupees and I will think about releasing him"),
        SpeechSegment(start_s=5.5, end_s=8.0, text="Don't even tell the police, I will kill him if I want to"),
    ]
    speech = SpeechResult(
        available=True,
        model="faster-whisper-base-int8",
        status="completed",
        language="en",
        duration_s=8.0,
        text=(
            "Your boy is in my hand, Mr. "
            "Give me 10 crore rupees and I will think about releasing him. "
            "Don't even tell the police, I will kill him if I want to."
        ),
        segments=segments,
    )

    fraud_res = fraud_engine.analyze(speech)

    # 1. Fraud Risk Assertions
    assert fraud_res.level == "HIGH", f"Expected HIGH, got {fraud_res.level}"
    assert any(act.action == "SEND_MONEY" for act in fraud_res.requested_actions), "Expected SEND_MONEY action"
    assert any(cat.category == "THREAT_PRESSURE" for cat in fraud_res.categories), "Expected THREAT_PRESSURE category"
    assert any(cat.category == "SECRECY" for cat in fraud_res.categories), "Expected SECRECY category"
    assert fraud_res.news_context_downgrade is False, "News downgrade must NOT fire on direct extortion threats"

    from app.schemas.evidence import EvidenceMatrix, EvidenceMetadata, EvidenceModalityResult, ProvenanceResult
    from app.schemas.reliability import ReliabilityResult
    from app.services.assessment_service import AssessmentService

    assessment_svc = AssessmentService()
    for media_verdict in ["LIKELY_MANIPULATED", "UNCERTAIN", "NO_STRONG_EVIDENCE", "SUSPICIOUS"]:
        matrix = EvidenceMatrix(
            visual=EvidenceModalityResult(level="HIGH"),
            audio=EvidenceModalityResult(level="HIGH"),
            provenance=ProvenanceResult(state="NONE_FOUND", note="No credentials found."),
            metadata=EvidenceMetadata(media_type="VIDEO", duration_s=8.0),
            reliability=ReliabilityResult(level="OK", reasons=[]),
        )
        assessment, explanations, _ = assessment_svc.assess(matrix, timeline=[], fraud=fraud_res)
        assert assessment.fraud == "HIGH"
        assert assessment.action == "STOP_AND_VERIFY", (
            f"Expected STOP_AND_VERIFY when fraud=HIGH, but got {assessment.action} for media={media_verdict}"
        )

