from typing import Optional
from pydantic import BaseModel, Field


class TimelineEvent(BaseModel):
    """
    Timestamped evidence event generated by Timeline Aggregation.
    Never claims more timestamp precision than the underlying detector provided.
    """
    start_s: float = Field(..., description="Start timestamp of the evidence window in seconds")
    end_s: float = Field(..., description="End timestamp of the evidence window in seconds")
    kind: str = Field(..., description="Evidence kind: 'visual' | 'audio' | 'transcript'")
    level: str = Field(
        ...,
        description="Evidence severity level: 'LOW' | 'MEDIUM' | 'HIGH' | 'N/A'"
    )
    evidence_source: str = Field(
        ...,
        description="Source of this observation: 'visual_window' | 'audio_window' | 'transcript_segment' | 'whole_file'"
    )
    score: Optional[float] = Field(
        None,
        description="Aggregated model score for this window (not a probability)"
    )
    details: Optional[str] = Field(
        None,
        description="Contextual details, such as transcribed text or window frame count"
    )
